//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class PlayerData {

	[SerializeField] private string characterName;
	[SerializeField] private int xp;
	[SerializeField] private int level;
	[SerializeField] private int rankPoints;
	[SerializeField] private List<SkillTreeSlot> skillTreeSlots;
	[SerializeField] private List<SkillID> skills;
	[SerializeField] private SkillID primarySkill;
	[SerializeField] private List<SkillID> secondarySkills;
	[SerializeField] private UnitData unitData;
	[SerializeField] private TeleportData teleportData;

	public PlayerData(PlayerData other){
		characterName = other.characterName;
		xp = other.xp;
		level = other.level;
		rankPoints = other.rankPoints;
		skillTreeSlots = new List<SkillTreeSlot>(other.skillTreeSlots);
		skills = new List<SkillID>(other.skills);
		primarySkill = new SkillID(other.primarySkill);
		secondarySkills = new List<SkillID>(other.secondarySkills);
		unitData = new UnitData(other.unitData);
		teleportData = new TeleportData(other.teleportData);
	}



	public string CharacterName => characterName;
	public int Xp => xp;
	public int Level => level;
	public int RankPoints => rankPoints;
	public List<SkillTreeSlot> SkillTreeSlots => skillTreeSlots;
	public List<SkillID> Skills => skills;
	public SkillID PrimarySkill => primarySkill;
	public List<SkillID> SecondarySkills => secondarySkills;
	public UnitData UnitData => unitData;
	public TeleportData TeleportData => teleportData;


}
	