//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class UnitData {

	[SerializeField] private string unitName;
	[SerializeField] private string raceName;
	[SerializeField] private int level;
	[SerializeField] private UnitAbilities abilities;
	[SerializeField] private UnitAttributes attributes;
	[SerializeField] private SkillID mainAttack;
	[SerializeField] private List<PerkID> perks;
	[SerializeField] private List<SkillID> skills;
	[SerializeField] private InventoryData inventory;
	[SerializeField] private bool isInitialized;

	public UnitData(UnitData other){
		unitName = other.unitName;
		raceName = other.raceName;
		level = other.level;
		abilities = new UnitAbilities(other.abilities);
		attributes = new UnitAttributes(other.attributes);
		mainAttack = new SkillID(other.mainAttack);
		perks = new List<PerkID>(other.perks);
		skills = new List<SkillID>(other.skills);
		inventory = new InventoryData(other.inventory);
		isInitialized = other.isInitialized;
	}



	public string UnitName => unitName;
	public string RaceName => raceName;
	public int Level => level;
	public UnitAbilities Abilities => abilities;
	public UnitAttributes Attributes => attributes;
	public SkillID MainAttack => mainAttack;
	public List<PerkID> Perks => perks;
	public List<SkillID> Skills => skills;
	public InventoryData Inventory => inventory;
	public bool IsInitialized => isInitialized;


}
	