//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class ComboData : IDeepCopyable {

	[SerializeField] private List<SkillData> skillDatas;
	[SerializeField] private List<int> dataIds;


	public ComboData(ComboData other){
		skillDatas = other.skillDatas.DeepCopy();
		dataIds = new List<int>(other.dataIds);
	}

	public object DeepCopy(){
		return new ComboData(this);
	}



	public List<SkillData> SkillDatas => skillDatas;
	public List<int> DataIds => dataIds;


}
	