//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class ItemData : IDeepCopyable , IUniqueName {

	[SerializeField] private string displayName;
	[SerializeField] private string uniqueName;
	[SerializeField, FoldoutGroup("Details", false), EnumToggleButtons] private ItemType typeFlags;
	[SerializeField, FoldoutGroup("Details", false), ShowIf("IsWeapon")] private WeaponData weaponData;
	[SerializeField, FoldoutGroup("Details", false)] private List<SkillID> skills;
	[SerializeField, FoldoutGroup("Details", false)] private List<PerkID> perks;
	[SerializeField, FoldoutGroup("Details", false)] private EquipmentSlotCombination[] slotCombinations;
	[SerializeField, FoldoutGroup("Details", false)] private ItemGraphics graphics;


	public ItemData(ItemData other){
		displayName = other.displayName;
		uniqueName = other.uniqueName;
		typeFlags = other.typeFlags;
		weaponData = new WeaponData(other.weaponData);
		skills = new List<SkillID>(other.skills);
		perks = new List<PerkID>(other.perks);
		slotCombinations = other.slotCombinations;
		graphics = other.graphics;
	}

	public object DeepCopy(){
		return new ItemData(this);
	}



	public string DisplayName => displayName;
	public string UniqueName => uniqueName;
	public ItemType TypeFlags => typeFlags;
	public WeaponData WeaponData => weaponData;
	public List<SkillID> Skills => skills;
	public List<PerkID> Perks => perks;
	public EquipmentSlotCombination[] SlotCombinations => slotCombinations;
	public ItemGraphics Graphics => graphics;


}
	