//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class AttackData {

	[SerializeField] private float damageMultiplier;
	[SerializeField] private AttackDamageType damageType;
	[SerializeField, ShowIf("ShowDamageRanges")] private int minDamage;
	[SerializeField, ShowIf("ShowDamageRanges")] private int maxDamage;

	public AttackData(AttackData other){
		damageMultiplier = other.damageMultiplier;
		damageType = other.damageType;
		minDamage = other.minDamage;
		maxDamage = other.maxDamage;
	}



	public float DamageMultiplier { get { return damageMultiplier; } }
	public AttackDamageType DamageType { get { return damageType; } }
	public int MinDamage { get { return minDamage; } }
	public int MaxDamage { get { return maxDamage; } }


}
	