//DO NOT EDIT - Autogenerated file
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Sirenix.OdinInspector;
using Teleports.Utils;

[System.Serializable]
public partial class HeroData : IDeepCopyable {

	[SerializeField] private bool isEmpty;
	[SerializeField] private string characterName;
	[SerializeField] private RaceID raceId;
	[SerializeField] private int xp;
	[SerializeField] private int level;
	[SerializeField] private int rankPoints;
	[SerializeField] private int totalAttributePoints;
	[SerializeField] private int spentAttributePoints;
	[SerializeField] private List<SkillTreeSlot> skillTreeSlots;
	[SerializeField] private List<SkillID> skills;
	[SerializeField] private SkillID primarySkill;
	[SerializeField] private List<SkillID> secondarySkills;
	[SerializeField] private UnitData unitData;
	[SerializeField] private TeleportData teleportData;

	public HeroData() {
		isEmpty = true;
	}

	public HeroData(HeroData other){
		isEmpty = other.isEmpty;
		characterName = other.characterName;
		raceId = other.raceId;
		xp = other.xp;
		level = other.level;
		rankPoints = other.rankPoints;
		totalAttributePoints = other.totalAttributePoints;
		spentAttributePoints = other.spentAttributePoints;
		skillTreeSlots = other.skillTreeSlots.DeepCopy();
		skills = other.skills.DeepCopy();
		primarySkill = new SkillID(other.primarySkill);
		secondarySkills = other.secondarySkills.DeepCopy();
		unitData = new UnitData(other.unitData);
		teleportData = new TeleportData(other.teleportData);
	}

	public object DeepCopy(){
		return new HeroData(this);
	}



	public bool IsEmpty => isEmpty;
	public string CharacterName => characterName;
	public RaceID RaceId => raceId;
	public int Xp => xp;
	public int Level => level;
	public int RankPoints => rankPoints;
	public int TotalAttributePoints => totalAttributePoints;
	public int SpentAttributePoints => spentAttributePoints;
	public List<SkillTreeSlot> SkillTreeSlots => skillTreeSlots;
	public List<SkillID> Skills => skills;
	public SkillID PrimarySkill => primarySkill;
	public List<SkillID> SecondarySkills => secondarySkills;
	public UnitData UnitData => unitData;
	public TeleportData TeleportData => teleportData;


}
	